# Continues deployment workflow to automatically
# deploy the website
name: Deploy Edge

on:
  push:
    branches:
      - 'main'

jobs:
  edge:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]
    environment:
      name: Staging
    env:
      IS_CI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mask hidden URLs
        run: |
          echo "::add-mask::${{ secrets.APP_URL }}"
          echo "::add-mask::${{ secrets.SSH_URL }}"
      - name: Do deployment
        uses: dokku/github-action@master
        with:
          branch: main
          git_push_flags: '--force'
          git_remote_url: ${{ secrets.DEPLOYMENT_HOST }}
          ssh_private_key: ${{ secrets.DEPLOYMENT_KEY }}
          ssh_host_key: ${{ secrets.DEPLOYMENT_HOST_KEY }}
